### ISSUE TITLE
.NET core

### ISSUE THREAD

**Issue by MegaXgh** [urbanoanderson/xinput-windows-manager#1]
it says I need .NET core I have downloaded .NET 7 but still, I installed the 2 and 3 but still 
![Screenshot 2023-06-05 123518](https://github.com/urbanoanderson/xinput-windows-manager/assets/86423310/a1a60aec-09ba-45ba-aef6-ab18131f96a5)

**Comment by urbanoanderson** [comment]
Sorry, I haven't messed with this in a while so I'm not sure if it still works. By the project file I can see it's using .NET Core 3.1. You can also try changing .NET version and recompiling it

**Comment by ShadoW-Shinigami** [comment]
Yeah recompiling with net 6.0 made the issue go away. Works perfectly! thank you for the software. (Have created a fork and uploaded the recompiled version there, hope you dont mind)

**Comment by urbanoanderson** [comment]
That's great to know, thank you so much! I'm merging your changes here as well
